### ISSUE TITLE
Useful links

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-local_assignsubmission_download#2]
The Useful links section at https://moodle.org/plugins/local_assignsubmission_download uses the same URL for multiple purposes.

* No need for "Website URL" if it is identical to "More documentation ..."
* Bug tracker URL should point directly to https://github.com/academic-moodle-cooperation/moodle-local_assignsubmission_download/issues
* What is the purpose of the "Discussion" link? Where here at Github should the discussion happen? Normally this field is used if there is a forum or a thread at moodle.org. If you do not have a dedicated place with online discussions about the plugin, better to leave empty.

**Comment by mudrd8mz** [comment]
Please note, the same applies for the other plugin https://moodle.org/plugins/report_offlinequizcron as well.

**Comment by mkemmerling** [comment]
Thanks for pointing this out. It actually applied to _all_ AMC plugins. Fixed it everywhere.
For now I removed the external documentation links for the two new plugins since the documentation people are still working on it.
