### ISSUE TITLE
Classes names violate Moodle naming guidelines

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-local_assignsubmission_download#4]
Things like https://github.com/academic-moodle-cooperation/moodle-local_assignsubmission_download/blob/92ca4f3ff3fd2b3a8477dca3ac071c75f23799b7/printpreview.class.php#L38 violate the Moodle coding guidelines on naming.

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

Ideally things like this should be refactored to auto-loaded classes.

**Comment by mudrd8mz** [comment]
It would also allow you to avoid things like https://github.com/academic-moodle-cooperation/moodle-local_assignsubmission_download/blob/92ca4f3ff3fd2b3a8477dca3ac071c75f23799b7/printpreview.class.php#L80-L81 that are discouraged as per https://docs.moodle.org/dev/Coding_style#Require_.2F_include

**Comment by goggo24** [comment]
Thanks for reporting, we have included it in our backlog. Cheers, Eva

**Comment by goggo24** [comment]
Fix will be included in v.3.10.1 and 3.11 - coming soon.
