### ISSUE TITLE
Invalid settings storage and names

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-local_assignsubmission_download#5]
The settings.php uses setting names such as `assignmentpatch_perpage` or `assignsubmission_download_showfilerenaming`. This is wrong for two reasons as per https://docs.moodle.org/dev/Plugin_contribution_checklist#Settings_storage

* If named like this, settings are stored in the main `mdl_config` table which then pollutes the global `$CFG` object.
* If named like this, some settings would actually be owned by a different plugin type - "assignsubmission" is a subplugin of the `mod_assign`.

Settings should better be named like `local_assignsubmission_download/showfilerenaming` and loaded via `get_config()`

**Comment by goggo24** [comment]
Thanks for reporting, we have included it in our backlog. Cheers, Eva

**Comment by goggo24** [comment]
Fix will be included in v.3.10.1 and 3.11 - coming soon.
