### ISSUE TITLE
Strings NOT in AMOS

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-local_assignsubmission_download#6]
Thanks for the plugin.
I'm a PT-PT tanslator.

In AMOS there are not strings to translate. Is it OK?
![imagem](https://user-images.githubusercontent.com/14828021/116828304-b92ad180-ab95-11eb-9960-7cf6278f71ff.png)

**Comment by mkemmerling** [comment]
No, not OK. Unfortunately we don't know yet why the plugin doesn't show up in AMOS. The lang directory with the english lang strings exists.

**Comment by dinism** [comment]
THANKS
I will wait for it in AMOS so the translation will be avaiable for all sites with the plugin.

**Comment by goggo24** [comment]
AMOS is now working. Have fun translating :)

**Comment by dinism** [comment]
The string datapreviewtitle is in deutch (Datenvorschau).

**Comment by goggo24** [comment]
Ahh - yes you are right. We will change it - in the meantime please overwrite it locally. Thanks.
